# Generated by Django 4.1.5 on 2023-01-26 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dish_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='menza_menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('id_dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menzaDatabase.dish_type')),
            ],
        ),
        migrations.CreateModel(
            name='menza_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='soup_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_user', models.IntegerField()),
                ('date', models.DateField(auto_now_add=True)),
                ('id_menza_menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menzaDatabase.menza_menu')),
            ],
        ),
        migrations.AddField(
            model_name='menza_menu',
            name='id_menza',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menzaDatabase.menza_type'),
        ),
        migrations.AddField(
            model_name='menza_menu',
            name='id_soup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menzaDatabase.soup_type'),
        ),
    ]
