# Generated by Django 4.1.5 on 2023-01-26 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menzaDatabase', '0002_review_rename_orders_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='id_order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='menzaDatabase.order'),
            preserve_default=False,
        ),
    ]
