# Generated by Django 4.1.5 on 2023-01-26 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_name_user_display_name_user_email_and_more'),
        ('menzaDatabase', '0003_review_id_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='id_user',
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.user'),
            preserve_default=False,
        ),
    ]
