# Generated by Django 4.1.5 on 2023-01-26 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.AddField(
            model_name='user',
            name='display_name',
            field=models.CharField(default='example_name', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.CharField(default='email', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='login_name',
            field=models.CharField(default='example_name', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='password', max_length=50),
        ),
    ]
