# Generated by Django 4.1.5 on 2023-01-27 18:50

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('menzaDatabase', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Diners',
            new_name='Diner',
        ),
        migrations.RenameModel(
            old_name='Dishes',
            new_name='Dish',
        ),
        migrations.RenameModel(
            old_name='Menus',
            new_name='Menu',
        ),
        migrations.RenameModel(
            old_name='Orders',
            new_name='Order',
        ),
        migrations.RenameModel(
            old_name='Reviews',
            new_name='Review',
        ),
        migrations.RenameModel(
            old_name='Soups',
            new_name='Soup',
        ),
    ]
