# Generated by Django 4.1.5 on 2023-02-10 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menzaDatabase', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='grade',
            new_name='rating',
        ),
    ]
