# Generated by Django 4.1.5 on 2023-01-27 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menzaDatabase', '0002_rename_diners_diner_rename_dishes_dish_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diner',
            name='display_name',
            field=models.CharField(default='test', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
