# Generated by Django 4.1.4 on 2023-04-30 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menzaDatabase', '0002_favoritediner'),
    ]

    operations = [
        migrations.AddField(
            model_name='diner',
            name='description',
            field=models.CharField(default='Placeholder description', max_length=500),
        ),
    ]
